### ISSUE TITLE
End of Math block sometimes cut off or accelerated in speech

### ISSUE THREAD

**Issue by bhavyashah** [NSoiffer/MathCATForPython#55]
I was reproducing this fairly consistently earlier today and now it is a 50-50. In the same NVDA session (no restarting NVDA, no file reopening, no disabling/re-enabling MathCAT add-on), I can experience this bug sometimes and not other times (both seem roughly equally likely). What this looks like for a simple Math block that reads "lambda sub 2" is as follows:
Normal: lambda sub 2, slow and steady and respecting the relative speech rate and everything is spoken normally
Buggy: lambda 2, with the sub entirely inaudible and the "oo" in the 2 very sped up or cut off
This is making it harder to process small Math blocks (that contain just a sigma or X or such) as well as the endings of Math blocks (esp. if they contain an important number). There is no difference in the NVDA log for both these behaviours. I am using Microsoft Edge 117.0.2045.47, NVDA 2023.3beta3, and MathCAT version 0.3.6. 
I arrow up to the Math block and it may read it in a normal or buggy manner, but identically log as follows:
IO - speech.speech.speak (22:50:31.219) - MainThread (9220):
Speaking ['clickable', RateCommand(multiplier=0.56), ' ', 'lambda sub 2', ' ', RateCommand()]

**Comment by NSoiffer** [comment]
For a previous bug related to espeak slowing down (#51), I had to "monkey patch" the espeak "speak" function.  I just double-checked, and the code I patched hasn't changed. My change simply got and reset the rate. I tried removing the patch and the problem was still there.

Here is what is getting sent to the espeak engine:
```
text=<prosody rate="39%"><say-as interpret-as="characters"><voice xml:lang="en-us">k</say-as>  is equal to  2  comma  3  comma  4    </prosody><mark name="657" /></voice>
```
As you might be able to tell, that's not properly nested XML. However, epeak doesn't seem to mind.  I pared this down to 
```
text=<prosody rate="39%"><say-as interpret-as="characters">k</say-as>  is equal to  2  comma  3  comma  4    </prosody>
```
And the problem persisted.

Since speech is cut off at the end, I tried add a `<break ...>` right before the end prosody tag. Eventually I cut the time all the way down to 1ms, and no cut off speech. It is a bit worrisome doing this because _all_ epeak code is potentially affected, not just MathCAT speech -- that's the nature of monkey patching. However, most speech I saw didn't use `<prosody>`, so maybe it doesn't affect too much.

There is [a new NVDA addon build here](https://github.com/NSoiffer/MathCATForPython/releases/download/v.0.3.7-beta.5/MathCAT-0.3.7.nvda-addonhttps://github.com/NSoiffer/MathCATForPython/releases/download/v.0.3.7-beta.5/MathCAT-0.3.7.nvda-addon). Please test and let me know if the problem is fixed. Also, do you notice the pause?

Please reopen if this doesn't fix the problem.

**Comment by bhavyashah** [comment]
I quickly tried the new build on the examples in my comment. Thanks for the fix - the speech cutoff seems to be gone. I will need to do further testing to comment on the pause. Also, the slowing down issue seems to persist for me so I will comment on #51.
